### ISSUE TITLE
Scan Box Style

### ISSUE THREAD

**Issue by klaemo** [klaemo/slubnav#11]
Hat jemand Ideen für die Scan Box? Sonderlich toll ist sie bis jetzt noch nicht.

Typo, Inhalt...alles

Think outside the :package:

**Comment by OlliLenz** [comment]
So Dudes ich hab jetzt erstmal so ne Idee gepusht, heißt style-scan-box, Kritik ist erwünscht ;)

**Comment by klaemo** [comment]
:+1: 
Find die Richtung gut. 
Paar Ideen: der Kameraknopf muss nicht sein, QR Scanner spucken immer automatisch das Ergebnis aus, wenn sie was gefunden haben. Ich bin mir nicht sicher ob klar ist, dass man einen Code eingeben kann. Vielleicht noch ein kleiner Hilfetext drunter? 
Und irgendwie sollte auch ersichtlich werden, dass man nur eins von beiden machen muss.

**Comment by sto3psl** [comment]
Richtung gefällt mir auch aber ich fühle mich von dem Kamera Icon etwas erschlagen. Die Nummer braucht irgendwie einen Text drüber. Jetzt steht sie einfach leer im Raum und man weiß nicht was sie machen soll. Vielleicht "Standort-Code:" als Label oder sowas. Die Linie ist mir persönlich zu lang und das Häkchen fände ich cooler neben dem Code.

**Comment by klaemo** [comment]
Gibt's hier noch was zu tun? Mergen?

**Comment by sto3psl** [comment]
Der Abstand zwischen QR-Code und Input Feld ist ganz schön groß.

**Comment by OlliLenz** [comment]
Das muss noch fertig gemacht werden ich setze mich gleich dran ;)

**Comment by OlliLenz** [comment]
Also folgendes ich hab keine Ideen wie ich das Scanboxfeld noch abändern kann, ich find auch dadurch das das so breit ist sieht das alles irgendwie nichtmehr so schick aus. Und falls jemand lust und Zeit hat kann er mal gucken wie man das Inputfeld mit dem Checkbutton näher an den Strich bekommt ohne das das Inputfeld den Strick überdeckt klappt bei mir nicht. Falls jemand doch noch irgendeine coole Idee hat bitte mitteilen dann kann ich das versuchen umzusetzen.

**Comment by sto3psl** [comment]
siehe Pull Request
