### ISSUE TITLE
Reworked Map

### ISSUE THREAD

**Issue by sto3psl** [klaemo/slubnav#16]
Ich habe mal zwei neue flat Karten gemacht. Wenn ihr Lust und Zeit habt könnt ihr sie euch ja mal anschauen und eure Meinung abgeben. Mir gefällt die helle ganz gut.
branch: reworked-map

**Comment by klaemo** [comment]
Die helle gefällt mir besser als die dunkle (in anderen Worten, die dunkle gefällt mir gar nicht). Der rote Pfad ist eventuell etwas dick. Trotz allem gefällt mir die Variante mit den Schatten noch am besten. 
Vielleicht kannst du die noch etwas tweaken? Dezentere Schatten und nicht-Regal-Elemente auch etwas zurückhaltender?

**Comment by OlliLenz** [comment]
Also ich muss sagen wenn wir es flach halten find ich die dunkle Map besser, weil es einfach besser gegliedert aussieht. Ansonsten fand ich die mit Schatten irgendwie auch bis jetzt am besten aber da ist halt schwierig ruhe rein zu bekommen.

**Comment by sto3psl** [comment]
<rant> Jeder verkackte Browser zeigt die verkackte SVG anders an!!!1einself </rant>
Achso und es gibt ne neue "revolutionary" Edition

**Comment by sto3psl** [comment]
Und noch eine neue Karte. Irgendwann wäre mal Feedback cool und nicht nur von Clemens.
Es gibt jetzt: Light, Dark, 3D, Outlines

**Comment by sto3psl** [comment]
Gibt ne finale Karte als Pull Request.
