### ISSUE TITLE
SVG Karten

### ISSUE THREAD

**Issue by klaemo** [klaemo/slubnav#3]
Ich denke wir brauchen 3 relativ simple, nicht unbedingt akkurate Karten in SVG.

Eine Ebene davon sollen wir mehr ausgestalten, mit 2-3 unterschiedlich detaillierten Zoomstufen.

Mein Vorschlag: 3 `.svg` Dateien (für jede Ebene eine), wobei eine detaillierter ist und gewissen Details über Selektoren (`.css-klassen`) aus-/eingeblendet werden können.
Die einzelnen Bereiche sollten als Gruppen auch per Selektor ansprechbar sein. Wir brauchen ja auch beispielhaft nur 3-4 Bereiche einzeichen oder so.

Zum erstellen werden sich Tools eignen die ordentliche (:tm:) SVGs ausspucken. Ich hab hier iDraw, das scheint relativ reine Dateien zu erstellen. Inkscape sollte auch ganz gut sein. Die Adobe Programme machen da ja bekanntermaßen immer noch viele eigene Anmerkungen rein.

**Comment by sto3psl** [comment]
I'm on it bro. :+1:

**Comment by sto3psl** [comment]
In svg-map ist eine neue map provisorisch eingebunden.
Bitte kritisieren und wenn euch was im Kopf rumschwirrt immer sagen! :smiley:

**Comment by klaemo** [comment]
:+1: Hat ja schon alle Elemente die wir brauchen, glaub ich :) 

Wie ich schon mal gesagt hatte, würde ich abgerundete und gerade Ecken nicht mischen. Genauso Rahmen/kein Rahmen.
Bei den Farben wird es schwierig...da weiß ich echt nicht was wir machen sollten. Im moment ist das noch nicht mega, oder?
Und diese kleinen Renderingfehler oder was auch immer sind dir ja bekannt.

**Comment by klaemo** [comment]
Und wenn Dinge so 1-2px von der Wand entfernt sind, einfach direkt an die Wand schieben? Das sieht irgendwie unsauber aus sonst, finde ich

**Comment by OlliLenz** [comment]
Also das mit den Ecken stimme ich Clemens zu und die Farben das schaut so düster aus keine Ahnung wie ich das sonst beschreiben soll, aber ich hab genauso keine Ahnung was man da wirklich anders machen kann.

**Comment by klaemo** [comment]
Wir brauch auch noch die unsichtbaren Wege die wir dann einblenden können.
Überleg dir mal 2-3 Beispiel Verbindungen.

**Comment by sto3psl** [comment]
Es sind 3 Verbindungen drin. :rocket:
