### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by klaemo** [klaemo/slubnav#8]
Wir brauchen vielleicht irgendeine Art Raster für das Layout, oder?
Ich hab schon mal mit [pure grids](http://purecss.io/grids/) gearbeitet. Das scheint ganz minimalistisch zu sein.

Wir können natürlich auch irgendwie unsere eigenen Maße festlegen.

@sto3psl @leokaessner was sagt ihr?

**Comment by sto3psl** [comment]
Wäre vermutlich nicht verkehrt und macht die Anja glücklich.
Sollten wir uns schnell einigen damit wir später nicht so viel anpassen müssen und gleich mit dem Grid arbeiten. 
@klaemo  Würdest du das mit eigenen Maße über CSS Variablen festlegen?

**Comment by klaemo** [comment]
Ich hab mir noch keine Gedanken gemacht, wie man das selber am
besten umsetzt. 
Ich würde sagen, wir nehmen ein fertiges Gridsystem. 

---

Clemens
